config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: "user_registrations" }

  resources :users
  
  root 'simple_pages#index'

  get 'contact', to: 'simple_pages#contact', as: 'contact'

  post 'simple_pages/thank_you'
  
  resources :orders, only: [:index, :show, :create, :destroy]
  
  resources :products do
    resources :comments
  end

  post 'payments/create'

  mount ActionCable.server => '/cable'
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Practice</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <!-- CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <link href="https://fonts.googleapis.com/css?family=Quicksand" rel="stylesheet">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.3.1/css/all.css" integrity="sha384-mzrmE5qonljUremFsqc01SB46JvROS7bZs3IO2EmfFsd15uHvIt+Y8vEf7N7fWAU" crossorigin="anonymous">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <!-- JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.min.js" integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <%= link_to "Bikes", products_path, class: 'navbar-brand' %>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item">
            <%= link_to "Home", products_path, class: 'nav-link' %>
          </li>
          <li class="nav-item">
            <%= link_to "Contact Us", contact_path, class: 'nav-link' %>
          </li>
          <% if user_signed_in? %>
            <li class="nav-item">
              <%= link_to('Logout', destroy_user_session_path, method: :delete, class: "nav-link") %>
            </li>
          <% else %>
            <li class="nav-item">
              <%= link_to('Login', new_user_session_path, class: "nav-link") %>
            </li>
          <% end %>
        </ul>
        <%= form_with(url: products_path, method: 'get', local: true, class: 'form-inline my-2 my-lg-0"') do |form| %>
          <%= form.text_field :q, id: 'q', value: params[:q], class: 'form-control mr-sm-2',  placeholder: 'Search' %>
          <%= form.submit 'Search', class: 'btn btn-outline-success my-2 my-sm-0' %>
        <% end %>
      </div>
    </nav>
    <% flash.each do |key, value| %>
      <script type="text/javascript">
        alert('<%== value %>')
      </script>
    <% end %>
    
    <%= yield %>
  </body>
</html>